
name: eBook Automation

on:
  push:
    branches: [ main ]

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install LibreOffice
        run: sudo apt-get update && sudo apt-get install -y libreoffice

      - name: Convert DOCX to PDF
        run: libreoffice --headless --convert-to pdf "Data Security.docx" --outdir ./output

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: eBook-PDF
          path: ./output/YourDocument.pdf

